name: Sync For & Gitlab mirror
on:
  schedule:
    - cron: '0 0 * * MON,WED,FRI,SUN'
  workflow_dispatch:
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: Ryujinx
          repo: Ryujinx
          auto_approve: true
          ignore_fail: true
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ secrets.TARGET_URL }}
          target-username: ${{ secrets.TARGET_USERNAME }}
          target-token: ${{ secrets.TARGET_TOKEN }}
